coverage:
  status:
    project:
      default:
        target: 80%  # Cobertura mínima esperada
        threshold: 2%  # Tolerancia de caída
    patch:
      default:
        target: 70%

ignore:
  - "tests/**"
  - "**/__init__.py"
  - "**/migrations/**"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
